In [50]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.feature_extraction import DictVectorizer
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn import svm,tree
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import Imputer,scale,LabelEncoder, OneHotEncoder
from gensim.models import Word2Vec
from sklearn.metrics import r2_score,mean_squared_error, explained_variance_score, accuracy_score
from scipy import sparse
from scipy.sparse import hstack,vstack

# Deep Learning 
import tensorflow as tf
import keras
from keras.models import Sequential
from keras.layers import Dense,LSTM,Dropout, Activation
from keras.optimizers import SGD
from keras.wrappers.scikit_learn import KerasRegressor
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import KFold
from sklearn.pipeline import Pipeline

In [51]:
df = pd.read_csv('Claims2.csv',encoding='mac_roman', low_memory=False)
df1 = pd.read_csv('Claims.csv',encoding='mac_roman', low_memory=False)
columns_to_be_dropped =['PLATE','PLATESTATE','EMPLSTATUS','EMPLSTATUSDESC','EMPLSTATUS_NCCI','DOB','DATEOFHIRE','NCCI_NOI','NCCI_SOI','NCCI_SEV','JOBCODE','JOBTITLE','CLASSCODE','CLASSCODE_DESCR','IPHONE','IWORKPHONE','LNAME','LTAXID','LADDR1','LADDR2','LCITY','LSTATE','LZIP','LPHONE','LFAX','DNAME','DTAXID','DADDR1','DADDR2','DCITY','DSTATE','DZIP','DPHONE','DFAX','CLASSCODE','CLASSCODE_DESCR','DATEINITIA','DATERETURN','DATEREPORT','WEEKLYWAGE','DIVTXTCODE','INSUIT','DEFENSECOUNSEL','SUITRECEIVED','APPARENTSERVICEDATE','SUITASSIGNED','STIPDATE','DCTAXID','DCCONTACT','DCADDR1','DCADDR2','DCCITY','DCSTATE','DCZIP','DCPHONE','DCFAX','ISSNUM',
'CLIENTSCLMNO','THIRDNUM','MARITAL','INDRESERVES','MEDRESERVES','EXPRESERVES','TOTALRESERVES','PHP_1st_Deducible_Notice','PHP_AMSLocs','PHP_Baileys_Custom_Location','PHP_Corrigan_Location','PHP_Daryl_Flood_Locs','PHP_Date_of_Expected_Denial','PHP_Date_of_Recovery','PHP_Deductible_Explanation','PHP_Deductible_Verifies?','PHP_Employee_Theft','PHP_Hazen_CC#','PHP_Mysterious_Disappearance','NET_INDEMNITY_RESERVE','NET_EXPENSE_RESERVE','PHP_Order_Number','PHP_Owner_Retained_Salvage_Amount','PHP_Cause_Code','PHP_Ref._to_Carrier_for_Recovery','PHP_Salvage','PHP_TF_Final_Mile_Branch_Code','PHP_TF/Final_Mile_Contractor','PHP_UST_Branch_Code','PHP_Van_Line','PHP_Voluntary_Payment']
df1.drop(columns=columns_to_be_dropped, inplace=True)

In [52]:
df

OCCURRENCE  LOSSDATE LOB                  COVERAGE STATE  \
0      LXMS-8139  20121231  AL    PROPERTY DAMAGE - AUTO    TX   
1      ZUHG-5230  20121231  IM         MOTOR TRUCK CARGO    FL   
2      ZUMS-4898  20121231  AL             COMPREHENSIVE    CA   
3      LXMS-7274  20121231  AL    PROPERTY DAMAGE - AUTO    AR   
4      LXMS-7268  20121231  GL      PROPERTY DAMAGE - GL    TX   
5      ZUMS-4938  20121231  AL                 COLLISION    CA   
6      ZUMS-4898  20121231  AL             COMPREHENSIVE    CA   
7      ZUMS-4885  20121231  AL    PROPERTY DAMAGE - AUTO    TX   
8      ZUMS-8695  20121230  GL      PROPERTY DAMAGE - GL    CO   
9      LXMS-7913  20121230  AL    PROPERTY DAMAGE - AUTO    OR   
10     ZUMS-6356  20121230  AL    PROPERTY DAMAGE - AUTO    MO   
11     ZUHG-6319  20121230  IM         MOTOR TRUCK CARGO    MO   
12     LXHG-4298  20121230  IM         MOTOR TRUCK CARGO    TN   
13     ZUMS-5343  20121230  AL    PROPERTY DAMAGE - AUTO    TX   
14     ZUMS-5032  20121230  AL             COMPREHENSIVE    MN   
15     LXMS-7278  20121230  AL    PROPERTY DAMAGE - AUTO    NY   
16     ZUMS-8450  20121229  AL    PROPERTY DAMAGE - AUTO    NC   
17     ZUYG-5224  20121229  IM         MOTOR TRUCK CARGO    PA   
18     LXMS-7312  20121229  AL    PROPERTY DAMAGE - AUTO    PA   
19     ZUMS-5110  20121229  AL    PROPERTY DAMAGE - AUTO    OH   
20     LXHG-4244  20121229  IM         MOTOR TRUCK CARGO    NY   
21     ZUMS-7496  20121228  AL      BODILY INJURY - AUTO    NC   
22     ZUMS-4903  20121228  AL         P.I.P. (NO FAULT)    NY   
23     ZUMF-6068  20121228  IM         MOTOR TRUCK CARGO    CO   
24     LXMS-7504  20121228  AL    PROPERTY DAMAGE - AUTO    MA   
25     LXHG-4340  20121228  IM         MOTOR TRUCK CARGO    MO   
26     LXMS-7431  20121228  IM  BURGLARY,PILFERAGE,THEFT    WA   
27     LXYG-4315  20121228  IM         MOTOR TRUCK CARGO    MI   
28     LXHG-4266  20121228  IM         MOTOR TRUCK CARGO    PA   
29     LXHG-4260  20121228  IM         MOTOR TRUCK CARGO    PA   
...          ...       ...  ..                       ...   ...   
20064  LXMS-0010  20020521  GL      PROPERTY DAMAGE - GL    TX   
20065  LXMS-0010  20020521  GL      PROPERTY DAMAGE - GL    TX   
20066  LXMS-0010  20020521  GL      PROPERTY DAMAGE - GL    TX   
20067  LXMS-0010  20020521  GL      PROPERTY DAMAGE - GL    TX   
20068  LXMS-0010  20020521  GL      PROPERTY DAMAGE - GL    TX   
20069  LXMS-0010  20020521  GL      PROPERTY DAMAGE - GL    TX   
20070  LXMS-0010  20020521  GL      PROPERTY DAMAGE - GL    TX   
20071  LXMS-0010  20020521  GL      PROPERTY DAMAGE - GL    TX   
20072  LXMS-0010  20020521  GL      PROPERTY DAMAGE - GL    TX   
20073  LXMS-0010  20020521  GL      PROPERTY DAMAGE - GL    TX   
20074  LXMS-0010  20020521  GL      PROPERTY DAMAGE - GL    TX   
20075  LXMS-0010  20020521  GL      PROPERTY DAMAGE - GL    TX   
20076  LXMS-0010  20020521  GL      PROPERTY DAMAGE - GL    TX   
20077  LXMS-0010  20020521  GL      PROPERTY DAMAGE - GL    TX   
20078  LXMS-0010  20020521  GL      PROPERTY DAMAGE - GL    TX   
20079  LXMS-0010  20020521  GL      PROPERTY DAMAGE - GL    TX   
20080  LXMS-0008  20020518  AL    PROPERTY DAMAGE - AUTO    CA   
20081  LXMS-0065  20020513  AL    PROPERTY DAMAGE - AUTO    CA   
20082  LXMS-0013  20020510  AL             COMPREHENSIVE    CA   
20083  LXMS-0012  20020506  AL             COMPREHENSIVE    CA   
20084  LXMS-0004  20020419  AL    PROPERTY DAMAGE - AUTO    CA   
20085  LXMS-0004  20020419  AL                 COLLISION    CA   
20086  LXMS-0005  20020415  AL    PROPERTY DAMAGE - AUTO    PA   
20087  LXMS-0005  20020415  AL    PROPERTY DAMAGE - AUTO    PA   
20088  LXMS-0006  20020411  AL    PROPERTY DAMAGE - AUTO    FL   
20089  LXMS-0001  20020410  CO           FALLING OBJECTS    FL   
20090  LXMS-0007  20020405  AL             COMPREHENSIVE    CA   
20091  LXMS-0003  20020405  AL    PROPERTY DAMAGE - AUTO    FL   
20092  LXMS-0002  20020404  AL                

# TensorFlow

In [53]:
hello=tf.constant('umm hello?')
sess=tf.Session()
print(sess.run(hello))

b'umm hello?'


In [54]:
df=df.fillna('Unknown')
print(df.isnull().sum())

OCCURRENCE    0
LOSSDATE      0
LOB           0
COVERAGE      0
STATE         0
DESCR         0
CADDR1        0
CSTATE        0
CZIP          0
LOCNM         0
IZIP          0
DRIVERAGE     0
INCURRED      0
PREMIUM       0
TOTALPAID     0
dtype: int64


In [55]:
X = df.iloc[:,1:11].values
y = df.iloc[:, 12].values
X[0]

array([20121231, 'AL', 'PROPERTY DAMAGE - AUTO', 'TX', 'DAMAGE TO FLOOR',
       '2025 Umar Ave', 'TX', '78504', 'JONES MOVING & STORAGE COMPANY',
       '75356'], dtype=object)

In [56]:
labelencoder_X_1 = LabelEncoder()
X[:, 0] = labelencoder_X_1.fit_transform(X[:, 0])
labelencoder_X_2 = LabelEncoder()
X[:, 1] = labelencoder_X_2.fit_transform(X[:, 1])
labelencoder_X_1 = LabelEncoder()
X[:, 2] = labelencoder_X_1.fit_transform(X[:, 2])
labelencoder_X_1 = LabelEncoder()
X[:, 3] = labelencoder_X_2.fit_transform(X[:, 3])
labelencoder_X_1 = LabelEncoder()
X[:, 4] = labelencoder_X_1.fit_transform(X[:, 4])
labelencoder_X_1 = LabelEncoder()
X[:, 5] = labelencoder_X_1.fit_transform(X[:, 5])
labelencoder_X_2 = LabelEncoder()
X[:, 6] = labelencoder_X_2.fit_transform(X[:, 6])
labelencoder_X_1 = LabelEncoder()
X[:, 7] = labelencoder_X_1.fit_transform(X[:, 7])
labelencoder_X_1 = LabelEncoder()
X[:, 8] = labelencoder_X_2.fit_transform(X[:, 8])
labelencoder_X_1 = LabelEncoder()
X[:, 9] = labelencoder_X_1.fit_transform(X[:, 9])
X

array([[3363, 0, 39, ..., 4413, 1743, 982],
       [3363, 5, 29, ..., 2211, 3303, 552],
       [3363, 0, 10, ..., 4597, 1735, 1113],
       ...,
       [2, 0, 39, ..., 2301, 3246, 525],
       [1, 0, 9, ..., 6000, 1218, 1523],
       [0, 0, 39, ..., 2107, 3246, 525]], dtype=object)

In [57]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2)
y_train.shape

(16075,)

# keras with Tensorflow backend

# 10 features in y

In [58]:
def createNewY(y_test):
    newy=[]
    # 0, 10, 100, 1000, 10000, 100000, 1000000, 10000000
    for i in y_test:
        if(i<10):
            newy.append([1,0,0,0,0,0,0,0])
        elif(i>=10 and i<100):
            newy.append([0,1,0,0,0,0,0,0])
        elif(i>=100 and i<1000):
            newy.append([0,0,1,0,0,0,0,0])
        elif(i>=1000 and i<10000):
            newy.append([0,0,0,1,0,0,0,0])
        elif(i>=10000 and i<100000):
            newy.append([0,0,0,0,1,0,0,0])
        elif(i>=100000 and i<1000000):
            newy.append([0,0,0,0,0,1,0,0])
        elif(i>=1000000 and i<10000000):
            newy.append([0,0,0,0,0,0,1,0])
        elif(i>=10000000):
            newy.append([0,0,0,0,0,0,0,1])
    return newy
def createNewY1(y_test):
    newy=[]
    # 0, 10, 100, 1000, 10000, 100000, 1000000, 10000000
    for i in y_test:
        if(i<10):
            newy.append(0)
        elif(i>=10 and i<100):
            newy.append(1)
        elif(i>=100 and i<1000):
            newy.append(2)
        elif(i>=1000 and i<10000):
            newy.append(3)
        elif(i>=10000 and i<100000):
            newy.append(4)
        elif(i>=100000 and i<1000000):
            newy.append(5)
        elif(i>=1000000 and i<10000000):
            newy.append(6)
        elif(i>=10000000):
            newy.append(7)
    return newy

In [59]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2)
y_train[0]

0

In [60]:
newy=createNewY(y)
newy=np.asarray(newy)
X_train, X_test, y_train, y_test = train_test_split(X, newy, test_size = 0.2)
y_train[0]

array([0, 0, 0, 0, 0, 1, 0, 0])

In [61]:
model = Sequential()
model.add(Dense(5000, activation='relu', input_dim=X_train.shape[1]))
model.add(Dropout(0.1))
model.add(Dense(600, activation='relu'))
model.add(Dropout(0.1))
model.add(Dense(y_train.shape[1], activation='linear'))

sgd = SGD(lr=0.01, decay=1e-6, momentum=0.9, nesterov=True)
model.compile(loss='categorical_crossentropy',
              optimizer='adam',
              metrics=['accuracy',])

model.fit(X_train, y_train,epochs=10,batch_size=2000)
y_pred=model.predict(X_test)
score = model.evaluate(X_test, y_test, batch_size=2000)
score

Epoch 1/10
16075/16075 [==============================] - 6s 350us/step - loss: 2.5953 - acc: 0.0425
Epoch 2/10
16075/16075 [==============================] - 5s 319us/step - loss: 8.1348 - acc: 0.0345
Epoch 3/10
16075/16075 [==============================] - 5s 319us/step - loss: 15.3080 - acc: 0.0373
Epoch 4/10
16075/16075 [==============================] - 5s 324us/step - loss: 14.3384 - acc: 0.0391
Epoch 5/10
16075/16075 [==============================] - 5s 329us/step - loss: 13.8478 - acc: 0.0411
Epoch 6/10
16075/16075 [==============================] - 5s 333us/step - loss: 13.7532 - acc: 0.0855
Epoch 7/10
16075/16075 [==============================] - 5s 331us/step - loss: 8.2552 - acc: 0.1004
Epoch 8/10
16075/16075 [==============================] - 6s 384us/step - loss: 2.4319 - acc: 0.1004
Epoch 9/10
16075/16075 [==============================] - 6s 366us/step - loss: 2.4516 - acc: 0.1004
Epoch 10/10
4019/4019 [==============================] - 0s 117us/step


[2.3621700775211028, 0.09305797534725743]

In [62]:
def accuracy1(y_pred, y_test):
    count=0
    for i,j in zip(y_pred.round(), y_test):
        flag=1
        for k in range(8):
            if(i[k]!=j[k]):
                flag=0
            k+=1
        if(flag==1):
            count+=1
        
    return count/len(y_test)*100
                

In [63]:
accuracy1(y_pred,y_test)

0.0

In [64]:
y_pred[1]

array([-55965.035,   6956.351,  19903.344,  45379.71 , -63511.06 ,
       -58521.633,  67191.34 ,  16932.887], dtype=float32)

In [65]:
y


array([     0, 105194, 326204, ..., 298748, 102094,  32975], dtype=int64)

# pfft.

In [79]:
y=df1.iloc[0:,57]
newy=createNewY(y)
newy=np.asarray(newy)
X_train, X_test, y_train, y_test = train_test_split(X, newy, test_size = 0.2)
y_train[0]

array([0, 0, 0, 0, 1, 0, 0, 0])

In [80]:
classifier = Sequential()
# Adding the input layer and the first hidden layer
classifier.add(Dense(activation="relu", input_dim=X_train.shape[1], units=6, kernel_initializer="uniform"))
# Adding the second hidden layer
classifier.add(Dropout(0.2))
classifier.add(Dense(activation="relu", units=10, kernel_initializer="uniform"))
# Adding the output layer
classifier.add(Dropout(0.2))
classifier.add(Dense(activation="relu", units=8, kernel_initializer="uniform"))
classifier.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])
classifier.fit(X_train, y_train, batch_size = 100, epochs = 30)

Epoch 1/30
16075/16075 [==============================] - 1s 36us/step - loss: 0.8207 - acc: 0.8528
Epoch 2/30
16075/16075 [==============================] - 0s 13us/step - loss: 0.3465 - acc: 0.8725
Epoch 3/30
16075/16075 [==============================] - 0s 13us/step - loss: 0.3147 - acc: 0.8727
Epoch 4/30
16075/16075 [==============================] - 0s 13us/step - loss: 0.3050 - acc: 0.8726
Epoch 5/30
16075/16075 [==============================] - 0s 13us/step - loss: 0.3003 - acc: 0.8724
Epoch 6/30
16075/16075 [==============================] - 0s 12us/step - loss: 0.2982 - acc: 0.8730
Epoch 7/30
16075/16075 [==============================] - 0s 13us/step - loss: 0.2962 - acc: 0.8736
Epoch 8/30
16075/16075 [==============================] - 0s 13us/step - loss: 0.2951 - acc: 0.8734
Epoch 9/30
16075/16075 [==============================] - 0s 13us/step - loss: 0.2942 - acc: 0.8739
Epoch 10/30
16075/16075 [==============================] - 0s 13us/step - loss: 0.2933 - acc: 0.8731

In [81]:
y_pred=classifier.predict(X_test)
y_pred

array([[0.17895411, 0.        , 0.        , ..., 0.42323256, 0.08533149,
        0.        ],
       [0.17909455, 0.        , 0.        , ..., 0.48457247, 0.09458645,
        0.        ],
       [0.17909455, 0.        , 0.        , ..., 0.48457247, 0.09458645,
        0.        ],
       ...,
       [0.17909455, 0.        , 0.        , ..., 0.48457247, 0.09458645,
        0.        ],
       [0.17909455, 0.        , 0.        , ..., 0.48457247, 0.09458645,
        0.        ],
       [0.17193207, 0.        , 0.        , ..., 0.45462593, 0.08679104,
        0.        ]], dtype=float32)

In [82]:
score = classifier.evaluate(X_test, y_test, batch_size=2000)
score

4019/4019 [==============================] - 0s 35us/step


[0.2901220457764163, 0.8748755702986649]

In [70]:
def accuracy2(y_pred,y_test):
    l=len(y_pred)
    count=0
    for i in range(l):
        m=max(y_pred[i])
       # print(m)
        index= np.where(y_pred[i]==m)
        #print(index)
        one = np.where(y_test[i]==1)
        #print(one)
        if(one[0]==index[0]):
            count+=1
        elif(one[0]==(index[0]-1) or one[0]==(index[0]+1)):
            count+=1
    return count/l*100

In [71]:
accuracy2(y_pred,y_test)

88.2060213983578

In [72]:
y_pred[4]

array([0.12167519, 0.        , 0.        , 0.        , 0.61481917,
       0.25392786, 0.        , 0.        ], dtype=float32)

In [73]:
y_test[4]

array([0, 0, 0, 0, 0, 1, 0, 0])

In [74]:
for i in y_pred:
    print(i)

[0.12167519 0.         0.         0.         0.61481917 0.25392786
 0.         0.        ]
[0.12167519 0.         0.         0.         0.61481917 0.25392786
 0.         0.        ]
[0.12167519 0.         0.         0.         0.61481917 0.25392786
 0.         0.        ]
[0.12167519 0.         0.         0.         0.61481917 0.25392786
 0.         0.        ]
[0.12167519 0.         0.         0.         0.61481917 0.25392786
 0.         0.        ]
[0.12167519 0.         0.         0.         0.61481917 0.25392786
 0.         0.        ]
[0.12167519 0.         0.         0.         0.61481917 0.25392786
 0.         0.        ]
[0.11739978 0.         0.         0.         0.5655185  0.24739745
 0.         0.        ]
[0.12167519 0.         0.         0.         0.61481917 0.25392786
 0.         0.        ]
[0.12167519 0.         0.         0.         0.61481917 0.25392786
 0.         0.        ]
[0.11651476 0.         0.         0.         0.56020653 0.2464905
 0.         0.        ]


 0.         0.        ]
[0.11387178 0.         0.         0.         0.54129004 0.24368538
 0.         0.        ]
[0.12167519 0.         0.         0.         0.61481917 0.25392786
 0.         0.        ]
[0.12167519 0.         0.         0.         0.61481917 0.25392786
 0.         0.        ]
[0.12167519 0.         0.         0.         0.61481917 0.25392786
 0.         0.        ]
[0.12167519 0.         0.         0.         0.61481917 0.25392786
 0.         0.        ]
[0.12167519 0.         0.         0.         0.61481917 0.25392786
 0.         0.        ]
[0.12167519 0.         0.         0.         0.61481917 0.25392786
 0.         0.        ]
[0.12167519 0.         0.         0.         0.61481917 0.25392786
 0.         0.        ]
[0.11873163 0.         0.         0.         0.5735123  0.24876231
 0.         0.        ]
[0.12167519 0.         0.         0.         0.61481917 0.25392786
 0.         0.        ]
[0.12167519 0.         0.         0.         0.61481917 0.25392786

 0.         0.        ]
[0.12167519 0.         0.         0.         0.61481917 0.25392786
 0.         0.        ]
[0.12167519 0.         0.         0.         0.61481917 0.25392786
 0.         0.        ]
[0.12167519 0.         0.         0.         0.61481917 0.25392786
 0.         0.        ]
[0.12167519 0.         0.         0.         0.61481917 0.25392786
 0.         0.        ]
[0.12167519 0.         0.         0.         0.61481917 0.25392786
 0.         0.        ]
[0.12167519 0.         0.         0.         0.61481917 0.25392786
 0.         0.        ]
[0.12167519 0.         0.         0.         0.61481917 0.25392786
 0.         0.        ]
[0.12167519 0.         0.         0.         0.61481917 0.25392786
 0.         0.        ]
[0.12167519 0.         0.         0.         0.61481917 0.25392786
 0.         0.        ]
[0.12167519 0.         0.         0.         0.61481917 0.25392786
 0.         0.        ]
[0.12167519 0.         0.         0.         0.61481917 0.25392786

 0.         0.        ]
[0.12167519 0.         0.         0.         0.61481917 0.25392786
 0.         0.        ]
[0.12167519 0.         0.         0.         0.61481917 0.25392786
 0.         0.        ]
[0.12167519 0.         0.         0.         0.61481917 0.25392786
 0.         0.        ]
[0.11378511 0.         0.         0.         0.53950346 0.24355648
 0.         0.        ]
[0.12090775 0.         0.         0.         0.60386276 0.25256413
 0.         0.        ]
[0.12167519 0.         0.         0.         0.61481917 0.25392786
 0.         0.        ]
[0.12167519 0.         0.         0.         0.61481917 0.25392786
 0.         0.        ]
[0.12167519 0.         0.         0.         0.61481917 0.25392786
 0.         0.        ]
[0.12167519 0.         0.         0.         0.61481917 0.25392786
 0.         0.        ]
[0.12167519 0.         0.         0.         0.61481917 0.25392786
 0.         0.        ]
[0.12167519 0.         0.         0.         0.61481917 0.25392786

[0.12167519 0.         0.         0.         0.61481917 0.25392786
 0.         0.        ]
[0.12167519 0.         0.         0.         0.61481917 0.25392786
 0.         0.        ]
[0.12167519 0.         0.         0.         0.61481917 0.25392786
 0.         0.        ]
[0.12167519 0.         0.         0.         0.61481917 0.25392786
 0.         0.        ]
[0.12167519 0.         0.         0.         0.61481917 0.25392786
 0.         0.        ]
[0.12167519 0.         0.         0.         0.61481917 0.25392786
 0.         0.        ]
[0.12167519 0.         0.         0.         0.61481917 0.25392786
 0.         0.        ]
[0.12167519 0.         0.         0.         0.61481917 0.25392786
 0.         0.        ]
[0.12167519 0.         0.         0.         0.61481917 0.25392786
 0.         0.        ]
[0.12167519 0.         0.         0.         0.61481917 0.25392786
 0.         0.        ]
[0.12167519 0.         0.         0.         0.61481917 0.25392786
 0.         0.        ]

 0.         0.        ]
[0.12167519 0.         0.         0.         0.61481917 0.25392786
 0.         0.        ]
[0.12167519 0.         0.         0.         0.61481917 0.25392786
 0.         0.        ]
[0.12167519 0.         0.         0.         0.61481917 0.25392786
 0.         0.        ]
[0.12167519 0.         0.         0.         0.61481917 0.25392786
 0.         0.        ]
[0.12167519 0.         0.         0.         0.61481917 0.25392786
 0.         0.        ]
[0.12167519 0.         0.         0.         0.61481917 0.25392786
 0.         0.        ]
[0.12167519 0.         0.         0.         0.61481917 0.25392786
 0.         0.        ]
[0.12167519 0.         0.         0.         0.61481917 0.25392786
 0.         0.        ]
[0.12167519 0.         0.         0.         0.61481917 0.25392786
 0.         0.        ]
[0.12167519 0.         0.         0.         0.61481917 0.25392786
 0.         0.        ]
[0.12167519 0.         0.         0.         0.61481917 0.25392786

[0.12167519 0.         0.         0.         0.61481917 0.25392786
 0.         0.        ]
[0.12167519 0.         0.         0.         0.61481917 0.25392786
 0.         0.        ]
[0.12167519 0.         0.         0.         0.61481917 0.25392786
 0.         0.        ]
[0.12167519 0.         0.         0.         0.61481917 0.25392786
 0.         0.        ]
[0.12167519 0.         0.         0.         0.61481917 0.25392786
 0.         0.        ]
[0.12167519 0.         0.         0.         0.61481917 0.25392786
 0.         0.        ]
[0.12167519 0.         0.         0.         0.61481917 0.25392786
 0.         0.        ]
[0.12167519 0.         0.         0.         0.61481917 0.25392786
 0.         0.        ]
[0.12167519 0.         0.         0.         0.61481917 0.25392786
 0.         0.        ]
[0.12167519 0.         0.         0.         0.61481917 0.25392786
 0.         0.        ]
[0.12167519 0.         0.         0.         0.61481917 0.25392786
 0.         0.        ]

 0.         0.        ]
[0.12167519 0.         0.         0.         0.61481917 0.25392786
 0.         0.        ]
[0.12167519 0.         0.         0.         0.61481917 0.25392786
 0.         0.        ]
[0.11658886 0.         0.         0.         0.5606513  0.24656643
 0.         0.        ]
[0.12142397 0.         0.         0.         0.6112326  0.25348145
 0.         0.        ]
[0.12167519 0.         0.         0.         0.61481917 0.25392786
 0.         0.        ]
[0.11307574 0.         0.         0.         0.52499163 0.2403488
 0.         0.        ]
[0.12167519 0.         0.         0.         0.61481917 0.25392786
 0.         0.        ]
[0.12167519 0.         0.         0.         0.61481917 0.25392786
 0.         0.        ]
[0.12167519 0.         0.         0.         0.61481917 0.25392786
 0.         0.        ]
[0.11314772 0.         0.         0.         0.5264131  0.2416733
 0.         0.        ]
[0.12167519 0.         0.         0.         0.61481917 0.25392786
 

[0.12167519 0.         0.         0.         0.61481917 0.25392786
 0.         0.        ]
[0.12167519 0.         0.         0.         0.61481917 0.25392786
 0.         0.        ]
[0.11376745 0.         0.         0.         0.53913933 0.24353021
 0.         0.        ]
[0.12167519 0.         0.         0.         0.61481917 0.25392786
 0.         0.        ]
[0.12167519 0.         0.         0.         0.61481917 0.25392786
 0.         0.        ]
[0.12167519 0.         0.         0.         0.61481917 0.25392786
 0.         0.        ]
[0.12167519 0.         0.         0.         0.61481917 0.25392786
 0.         0.        ]
[0.12167519 0.         0.         0.         0.61481917 0.25392786
 0.         0.        ]
[0.12167519 0.         0.         0.         0.61481917 0.25392786
 0.         0.        ]
[0.12167519 0.         0.         0.         0.61481917 0.25392786
 0.         0.        ]
[0.12167519 0.         0.         0.         0.61481917 0.25392786
 0.         0.        ]

 0.         0.        ]
[0.12167519 0.         0.         0.         0.61481917 0.25392786
 0.         0.        ]
[0.12167519 0.         0.         0.         0.61481917 0.25392786
 0.         0.        ]
[0.12167519 0.         0.         0.         0.61481917 0.25392786
 0.         0.        ]
[0.12167519 0.         0.         0.         0.61481917 0.25392786
 0.         0.        ]
[0.113632   0.         0.         0.         0.5363474  0.24332878
 0.         0.        ]
[0.12167519 0.         0.         0.         0.61481917 0.25392786
 0.         0.        ]
[0.12167519 0.         0.         0.         0.61481917 0.25392786
 0.         0.        ]
[0.11640172 0.         0.         0.         0.5595281  0.24637465
 0.         0.        ]
[0.12167519 0.         0.         0.         0.61481917 0.25392786
 0.         0.        ]
[0.12167519 0.         0.         0.         0.61481917 0.25392786
 0.         0.        ]
[0.12167519 0.         0.         0.         0.61481917 0.25392786

# with total paid

In [75]:
X = df.iloc[:,1:11].values
y = df.iloc[:, 14].values
X[0]

array([20121231, 'AL', 'PROPERTY DAMAGE - AUTO', 'TX', 'DAMAGE TO FLOOR',
       '2025 Umar Ave', 'TX', '78504', 'JONES MOVING & STORAGE COMPANY',
       '75356'], dtype=object)

In [76]:
labelencoder_X_1 = LabelEncoder()
X[:, 0] = labelencoder_X_1.fit_transform(X[:, 0])
labelencoder_X_2 = LabelEncoder()
X[:, 1] = labelencoder_X_2.fit_transform(X[:, 1])
labelencoder_X_1 = LabelEncoder()
X[:, 2] = labelencoder_X_1.fit_transform(X[:, 2])
labelencoder_X_1 = LabelEncoder()
X[:, 3] = labelencoder_X_2.fit_transform(X[:, 3])
labelencoder_X_1 = LabelEncoder()
X[:, 4] = labelencoder_X_1.fit_transform(X[:, 4])
labelencoder_X_1 = LabelEncoder()
X[:, 5] = labelencoder_X_1.fit_transform(X[:, 5])
labelencoder_X_2 = LabelEncoder()
X[:, 6] = labelencoder_X_2.fit_transform(X[:, 6])
labelencoder_X_1 = LabelEncoder()
X[:, 7] = labelencoder_X_1.fit_transform(X[:, 7])
labelencoder_X_1 = LabelEncoder()
X[:, 8] = labelencoder_X_2.fit_transform(X[:, 8])
labelencoder_X_1 = LabelEncoder()
X[:, 9] = labelencoder_X_1.fit_transform(X[:, 9])
X

array([[3363, 0, 39, ..., 4413, 1743, 982],
       [3363, 5, 29, ..., 2211, 3303, 552],
       [3363, 0, 10, ..., 4597, 1735, 1113],
       ...,
       [2, 0, 39, ..., 2301, 3246, 525],
       [1, 0, 9, ..., 6000, 1218, 1523],
       [0, 0, 39, ..., 2107, 3246, 525]], dtype=object)

In [77]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2)
y_train.shape

(16075,)

# keras with Tensorflow backend

# 10 features in y

In [83]:
def createNewY(y_test):
    newy=[]
    # 0, 10, 100, 1000, 10000, 100000, 1000000, 10000000
    for i in y_test:
        if(i<10):
            newy.append([1,0,0,0,0,0,0,0])
        elif(i>=10 and i<100):
            newy.append([0,1,0,0,0,0,0,0])
        elif(i>=100 and i<1000):
            newy.append([0,0,1,0,0,0,0,0])
        elif(i>=1000 and i<10000):
            newy.append([0,0,0,1,0,0,0,0])
        elif(i>=10000 and i<100000):
            newy.append([0,0,0,0,1,0,0,0])
        elif(i>=100000 and i<1000000):
            newy.append([0,0,0,0,0,1,0,0])
        elif(i>=1000000 and i<10000000):
            newy.append([0,0,0,0,0,0,1,0])
        elif(i>=10000000):
            newy.append([0,0,0,0,0,0,0,1])
    return newy
def createNewY1(y_test):
    newy=[]
    # 0, 10, 100, 1000, 10000, 100000, 1000000, 10000000
    for i in y_test:
        if(i<10):
            newy.append(0)
        elif(i>=10 and i<100):
            newy.append(1)
        elif(i>=100 and i<1000):
            newy.append(2)
        elif(i>=1000 and i<10000):
            newy.append(3)
        elif(i>=10000 and i<100000):
            newy.append(4)
        elif(i>=100000 and i<1000000):
            newy.append(5)
        elif(i>=1000000 and i<10000000):
            newy.append(6)
        elif(i>=10000000):
            newy.append(7)
    return newy

In [84]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2)
y_train[0]

0

In [85]:
newy=createNewY(y)
newy=np.asarray(newy)
X_train, X_test, y_train, y_test = train_test_split(X, newy, test_size = 0.2)
y_train[0]

array([0, 0, 0, 0, 0, 1, 0, 0])

In [86]:
model = Sequential()
model.add(Dense(5000, activation='relu', input_dim=X_train.shape[1]))
model.add(Dropout(0.1))
model.add(Dense(600, activation='relu'))
model.add(Dropout(0.1))
model.add(Dense(y_train.shape[1], activation='linear'))

sgd = SGD(lr=0.01, decay=1e-6, momentum=0.9, nesterov=True)
model.compile(loss='categorical_crossentropy',
              optimizer='adam',
              metrics=['accuracy',])

model.fit(X_train, y_train,epochs=10,batch_size=2000)
y_pred=model.predict(X_test)
score = model.evaluate(X_test, y_test, batch_size=2000)
score

Epoch 1/10
16075/16075 [==============================] - 6s 401us/step - loss: 2.3342 - acc: 0.3388
Epoch 2/10
16075/16075 [==============================] - 6s 371us/step - loss: 1.2738 - acc: 0.4627
Epoch 3/10
16075/16075 [==============================] - 6s 362us/step - loss: 13.6182 - acc: 0.4627
Epoch 4/10
16075/16075 [==============================] - 6s 383us/step - loss: 15.3689 - acc: 0.4627
Epoch 5/10
16075/16075 [==============================] - 6s 352us/step - loss: 15.3503 - acc: 0.4627
Epoch 6/10
16075/16075 [==============================] - 6s 346us/step - loss: 15.3434 - acc: 0.4627
Epoch 7/10
16075/16075 [==============================] - 6s 381us/step - loss: 15.3290 - acc: 0.4627
Epoch 8/10
16075/16075 [==============================] - 6s 382us/step - loss: 15.3173 - acc: 0.4627
Epoch 9/10
16075/16075 [==============================] - 6s 382us/step - loss: 14.1520 - acc: 0.4626
Epoch 10/10
4019/4019 [==============================] - 1s 132us/step


[0.9344406399480084, 0.47723314076343204]

In [87]:
def accuracy1(y_pred, y_test):
    count=0
    for i,j in zip(y_pred.round(), y_test):
        flag=1
        for k in range(8):
            if(i[k]!=j[k]):
                flag=0
            k+=1
        if(flag==1):
            count+=1
        
    return count/len(y_test)*100
                

In [88]:
accuracy1(y_pred,y_test)

0.0

In [89]:
y_pred[1]

array([ 25192.459, -25075.13 , -21208.146, -49021.39 ,  30216.512,
        41203.47 ,  33663.89 , -22521.477], dtype=float32)

In [90]:
y


0              0
1         105194
2         326204
3         171322
4         907656
5        1400446
6         796769
7          77791
8        3043240
9         166000
10             0
11         17500
12         17500
13        448170
14        390462
15        196543
16        414159
17        172310
18        404035
19        438888
20         52139
21        700000
22         74165
23       5000000
24        143159
25         23500
26        295616
27        226050
28        161990
29        300395
          ...   
20064      25000
20065      30000
20066      25000
20067      25000
20068      30000
20069      25000
20070      25000
20071      25000
20072      30000
20073      25000
20074      30000
20075      25000
20076      30000
20077      10000
20078      25000
20079      60000
20080     213282
20081     264100
20082          0
20083          0
20084      79560
20085          0
20086          0
20087          0
20088      51760
20089     591063
20090      71020
20091     2987

# pfft.

In [91]:
newy=createNewY(y)
newy=np.asarray(newy)
X_train, X_test, y_train, y_test = train_test_split(X, newy, test_size = 0.2)
y_train[0]

array([1, 0, 0, 0, 0, 0, 0, 0])

In [92]:
classifier = Sequential()
# Adding the input layer and the first hidden layer
classifier.add(Dense(activation="relu", input_dim=X_train.shape[1], units=6, kernel_initializer="uniform"))
# Adding the second hidden layer
classifier.add(Dropout(0.2))
classifier.add(Dense(activation="relu", units=10, kernel_initializer="uniform"))
# Adding the output layer
classifier.add(Dropout(0.2))
classifier.add(Dense(activation="relu", units=8, kernel_initializer="uniform"))
classifier.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])
classifier.fit(X_train, y_train, batch_size = 100, epochs = 30)

Epoch 1/30
16075/16075 [==============================] - 1s 41us/step - loss: 0.5811 - acc: 0.8626
Epoch 2/30
16075/16075 [==============================] - 0s 12us/step - loss: 0.3617 - acc: 0.8717
Epoch 3/30
16075/16075 [==============================] - 0s 13us/step - loss: 0.3233 - acc: 0.8732
Epoch 4/30
16075/16075 [==============================] - 0s 13us/step - loss: 0.3082 - acc: 0.8737
Epoch 5/30
16075/16075 [==============================] - 0s 13us/step - loss: 0.3051 - acc: 0.8738
Epoch 6/30
16075/16075 [==============================] - 0s 13us/step - loss: 0.3019 - acc: 0.8742
Epoch 7/30
16075/16075 [==============================] - 0s 16us/step - loss: 0.2996 - acc: 0.8736
Epoch 8/30
16075/16075 [==============================] - 0s 13us/step - loss: 0.2977 - acc: 0.8740
Epoch 9/30
16075/16075 [==============================] - 0s 13us/step - loss: 0.2965 - acc: 0.8747
Epoch 10/30
16075/16075 [==============================] - 0s 14us/step - loss: 0.2955 - acc: 0.8740

In [93]:
y_pred=classifier.predict(X_test)
y_pred

array([[0.1774353 , 0.        , 0.        , ..., 0.49422437, 0.10829027,
        0.        ],
       [0.1774353 , 0.        , 0.        , ..., 0.49422437, 0.10829027,
        0.        ],
       [0.17201921, 0.        , 0.        , ..., 0.46936026, 0.09689193,
        0.        ],
       ...,
       [0.16333143, 0.        , 0.        , ..., 0.43658477, 0.09224166,
        0.        ],
       [0.17212673, 0.        , 0.        , ..., 0.47729146, 0.09934731,
        0.        ],
       [0.1774353 , 0.        , 0.        , ..., 0.49422437, 0.10829027,
        0.        ]], dtype=float32)

In [94]:
score = classifier.evaluate(X_test, y_test, batch_size=2000)
score

4019/4019 [==============================] - 0s 56us/step


[0.28287042781588273, 0.875]

In [95]:
def accuracy2(y_pred,y_test):
    l=len(y_pred)
    count=0
    for i in range(l):
        m=max(y_pred[i])
       # print(m)
        index= np.where(y_pred[i]==m)
        #print(index)
        one = np.where(y_test[i]==1)
        #print(one)
        if(one[0]==index[0]):
            count+=1
        elif(one[0]==(index[0]-1) or one[0]==(index[0]+1)):
            count+=0.5
    return count/l*100

In [97]:
accuracy2(y_pred,y_test)

62.353819358049265

In [98]:
y_pred[4]

array([0.1774353 , 0.        , 0.        , 0.0415719 , 0.16512614,
       0.49422437, 0.10829027, 0.        ], dtype=float32)

In [99]:
y_test[4]

array([0, 0, 0, 0, 1, 0, 0, 0])

In [100]:
for i in y_pred:
    print(i)

[0.1774353  0.         0.         0.0415719  0.16512614 0.49422437
 0.10829027 0.        ]
[0.1774353  0.         0.         0.0415719  0.16512614 0.49422437
 0.10829027 0.        ]
[0.17201921 0.         0.         0.04034724 0.17690247 0.46936026
 0.09689193 0.        ]
[0.16483566 0.         0.         0.03698687 0.27410692 0.42221346
 0.09958515 0.        ]
[0.1774353  0.         0.         0.0415719  0.16512614 0.49422437
 0.10829027 0.        ]
[0.1715051  0.         0.         0.04028493 0.1823906  0.4474234
 0.09025867 0.        ]
[0.17634946 0.         0.         0.0413213  0.16789168 0.4914817
 0.10730202 0.        ]
[0.1774353  0.         0.         0.0415719  0.16512614 0.49422437
 0.10829027 0.        ]
[0.1774353  0.         0.         0.0415719  0.16512614 0.49422437
 0.10829027 0.        ]
[0.16320525 0.         0.         0.03942672 0.2201902  0.43469906
 0.09283103 0.        ]
[0.16731371 0.         0.         0.03645851 0.28140926 0.41963634
 0.1003976  0.        ]
[

[0.1774353  0.         0.         0.0415719  0.16512614 0.49422437
 0.10829027 0.        ]
[0.1774353  0.         0.         0.0415719  0.16512614 0.49422437
 0.10829027 0.        ]
[0.19860312 0.         0.         0.0362285  0.24462898 0.43065554
 0.09468429 0.        ]
[0.20126496 0.         0.         0.03469993 0.25280988 0.41259137
 0.09523705 0.        ]
[0.1774353  0.         0.         0.0415719  0.16512614 0.49422437
 0.10829027 0.        ]
[0.16307195 0.         0.         0.03754697 0.2645893  0.42499685
 0.09845978 0.        ]
[0.20255733 0.         0.         0.03313149 0.2876848  0.4055618
 0.09959006 0.        ]
[0.1774353  0.         0.         0.0415719  0.16512614 0.49422437
 0.10829027 0.        ]
[0.1774353  0.         0.         0.0415719  0.16512614 0.49422437
 0.10829027 0.        ]
[0.1928415  0.         0.         0.03682338 0.22798882 0.42661697
 0.09260092 0.        ]
[0.1774353  0.         0.         0.0415719  0.16512614 0.49422437
 0.10829027 0.        ]


 0.10331148 0.        ]
[0.1774353  0.         0.         0.0415719  0.16512614 0.49422437
 0.10829027 0.        ]
[0.2188965  0.         0.         0.03314937 0.28495142 0.4205514
 0.09903111 0.        ]
[0.1774353  0.         0.         0.0415719  0.16512614 0.49422437
 0.10829027 0.        ]
[0.17887986 0.         0.         0.03720869 0.2399936  0.42419484
 0.09462853 0.        ]
[0.1774353  0.         0.         0.0415719  0.16512614 0.49422437
 0.10829027 0.        ]
[0.21077752 0.         0.         0.03375245 0.25713092 0.40904412
 0.09538022 0.        ]
[0.1774353  0.         0.         0.0415719  0.16512614 0.49422437
 0.10829027 0.        ]
[0.1820292  0.         0.         0.03863133 0.20961626 0.43613952
 0.09079383 0.        ]
[0.1774353  0.         0.         0.0415719  0.16512614 0.49422437
 0.10829027 0.        ]
[0.1774353  0.         0.         0.0415719  0.16512614 0.49422437
 0.10829027 0.        ]
[0.1774353  0.         0.         0.0415719  0.16512614 0.49422437


 0.10829027 0.        ]
[0.19341478 0.         0.         0.0366203  0.22696969 0.42346036
 0.0923707  0.        ]
[0.18377843 0.         0.         0.03599269 0.17734814 0.3903197
 0.07862885 0.        ]
[0.1774353  0.         0.         0.0415719  0.16512614 0.49422437
 0.10829027 0.        ]
[0.20035683 0.         0.         0.03413462 0.26794913 0.40962178
 0.09719545 0.        ]
[0.1774353  0.         0.         0.0415719  0.16512614 0.49422437
 0.10829027 0.        ]
[0.1711573  0.         0.         0.04024998 0.18498987 0.44232935
 0.0888849  0.        ]
[0.1774353  0.         0.         0.0415719  0.16512614 0.49422437
 0.10829027 0.        ]
[0.17624806 0.         0.         0.03946946 0.19740346 0.4380524
 0.08943679 0.        ]
[0.16309139 0.         0.         0.03782131 0.25810957 0.42641285
 0.09763829 0.        ]
[0.18074387 0.         0.         0.03756741 0.2277365  0.42615598
 0.09299181 0.        ]
[0.17450958 0.         0.         0.04098751 0.17219548 0.4873165
 0

 0.09642537 0.        ]
[0.16313238 0.         0.         0.03839932 0.2444571  0.4293962
 0.09590749 0.        ]
[0.16883683 0.         0.         0.0401126  0.18883517 0.46900195
 0.09889969 0.        ]
[0.1631866  0.         0.         0.03916366 0.2264036  0.43334126
 0.09361874 0.        ]
[0.1774353  0.         0.         0.0415719  0.16512614 0.49422437
 0.10829027 0.        ]
[0.17611161 0.         0.         0.03593969 0.2754796  0.41748527
 0.09924794 0.        ]
[0.1681303  0.         0.         0.04004509 0.19377576 0.45281586
 0.09421352 0.        ]
[0.19116491 0.         0.         0.03718299 0.22661306 0.4300534
 0.09256166 0.        ]
[0.17521904 0.         0.         0.04111622 0.17053592 0.4889226
 0.1060636  0.        ]
[0.1774353  0.         0.         0.0415719  0.16512614 0.49422437
 0.10829027 0.        ]
[0.18400583 0.         0.         0.03962663 0.2669388  0.42889798
 0.10478711 0.        ]
[0.20761363 0.         0.         0.0342356  0.25090197 0.41069606
 0

 0.10829027 0.        ]
[0.26813948 0.         0.         0.0250637  0.38446963 0.4013845
 0.10921092 0.        ]
[0.1774353  0.         0.         0.0415719  0.16512614 0.49422437
 0.10829027 0.        ]
[0.20165929 0.         0.         0.0356726  0.24898814 0.42685443
 0.09505866 0.        ]
[0.1774353  0.         0.         0.0415719  0.16512614 0.49422437
 0.10829027 0.        ]
[0.1919249  0.         0.         0.03572696 0.24792571 0.41733104
 0.09504183 0.        ]
[0.19103846 0.         0.         0.03677328 0.22518921 0.42267427
 0.09220265 0.        ]
[0.16726501 0.         0.         0.03998802 0.1960204  0.45974666
 0.09699878 0.        ]
[0.21200228 0.         0.         0.03389921 0.26574677 0.416659
 0.09665377 0.        ]
[0.1774353  0.         0.         0.0415719  0.16512614 0.49422437
 0.10829027 0.        ]
[0.1774353  0.         0.         0.0415719  0.16512614 0.49422437
 0.10829027 0.        ]
[0.1774353  0.         0.         0.0415719  0.16512614 0.49422437
 0

In [101]:
y_test

array([[0, 0, 0, ..., 1, 0, 0],
       [0, 0, 0, ..., 1, 0, 0],
       [1, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 1, 0, 0],
       [0, 0, 0, ..., 1, 0, 0],
       [0, 0, 0, ..., 0, 1, 0]])

In [102]:
y_pred

array([[0.1774353 , 0.        , 0.        , ..., 0.49422437, 0.10829027,
        0.        ],
       [0.1774353 , 0.        , 0.        , ..., 0.49422437, 0.10829027,
        0.        ],
       [0.17201921, 0.        , 0.        , ..., 0.46936026, 0.09689193,
        0.        ],
       ...,
       [0.16333143, 0.        , 0.        , ..., 0.43658477, 0.09224166,
        0.        ],
       [0.17212673, 0.        , 0.        , ..., 0.47729146, 0.09934731,
        0.        ],
       [0.1774353 , 0.        , 0.        , ..., 0.49422437, 0.10829027,
        0.        ]], dtype=float32)